services:
  mysql:
    image: mysql:8-alpine
    container_name: tln_mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: tln
      MYSQLDATA: /var/lib/mysql/data
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tln_network
    healthcheck:
      test: ["CMD-SHELL", "mysql_isready -U mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: tln_adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - tln_network
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    container_name: tln_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - tln_network
volumes:
  mysql_data:

networks:
  tln_network:
    driver: bridge
