export interface UserCvsEntity {
  id: number;
  userId: number | null;
  firestoreDocId: string | null;
  nama: string | null;
  displayName: string | null;
  applyCount: number;
  beratBadan: string;
  celanaDiatasMataKaki: string | null;
  ciriFisikCatatan: string | null;
  ciriFisikJenggot: string | null;
  ciriFisikJenisRambut: string | null;
  ciriFisikPanjangRambut: string | null;
  ciriFisikWajah: string | null;
  ciriFisikWarnaKulit: string | null;
  ciriFisikWarnaRambut: string | null;
  ciriFisikByAdmin: string;
  cvPendingExpiry: number;
  cvPublishExpiry: number;
  cvPublishState: string | null;
  hasFirstPublished: number;
  cvUnpublishedReason: string | null;
  referralId: string | null;
  daerahAsal: string | null;
  originCityId: string | null;
  originProvinceId: string | null;
  domisili: string | null;
  domicileCityId: string | null;
  domicileProvinceId: string | null;
  domicileLatitude: string; // decimal → string atau number tergantung setting
  domicileLongitude: string;
  foto: string | null;
  fotoBlurred: string | null;
  fotoKtp: string | null;
  akteCerai: string | null;
  gender: string | null;
  hasUnreadMessage: number;
  hobi: string | null;
  isAdminApproved: number;
  jumlahAnak: string | null;
  jumlahHafalanQuran: string | null;
  karakterDanSifat: string | null;
  parentPermission: string | null;
  kelompokNgaji: string | null;
  kriteriaDomisili: string | null;
  kriteriaLainnya: string | null;
  kriteriaPekerjaan: string | null;
  kriteriaUmurAkhir: string | null;
  kriteriaUmurAwal: string | null;
  lastUpdated: string | null;
  lastSessionActive: string | null;
  membershipState: string | null;
  vipStartDate: string | null;
  vipEndDate: string | null;
  menikahDenganPriaBeristri: string | null;
  merokok: string | null;
  panjangJilbab: string | null;
  pekerjaan: string | null;
  phone: string | null;
  publicUid: string | null;
  role: string | null;
  statusMenikah: string | null;
  suku: string | null;
  targetMenikah: string | null;
  tempatLahir: string | null;
  tglLahir: string | null;
  tinggiBadan: string | null;
  uid: string | null;
  viewCount: number;
  createdAt: Date | null;
  updatedAt: Date | null;
}

export interface userCvsList {
  id: number;
  userId: number | null;
  firestoreDocId: string | null;
  nama: string | null;
  cvPublishState: string | null;
  cvPublishExpiry: number | null;
  cvPendingExpiry: number | null;
  uid: string | null;
  publicUid: string | null;
}
